program liljs_castle_standalone;

{ This is a standalone program for "Lil J's Castle".
  It uses Castle Game Engine.
  This file is automatically generated by Castle Game Engine build tool. }

{$ifdef CASTLE_AUTO_GENERATED_RESOURCES}
  {$R castle-auto-generated-resources.res}
{$endif}

uses CastleWindow, GameInitialize;

begin
  Application.MainWindow.OpenAndRun;
end.

